# Platform
platform :ios, '14.0'

# Source
source 'https://cdn.cocoapods.org/'

# Inhibit all warnings
inhibit_all_warnings!

# Use frameworks
use_frameworks! :linkage => :static

target "PhotoBrowserDemo" do
  pod 'SDWebImage'
  pod 'DACircularProgress'
  pod 'pop'
end
